<?php
define('PSM_DB_HOST', $_SERVER['MYSQLPSM_PORT_3306_TCP_ADDR']);
define('PSM_DB_NAME', $_SERVER['MYSQLPSM_ENV_MYSQL_DATABASE']);
define('PSM_DB_USER', $_SERVER['MYSQLPSM_ENV_MYSQL_USER']);
define('PSM_DB_PASS', $_SERVER['MYSQLPSM_ENV_MYSQL_PASSWORD']);
define('PSM_DB_PREFIX', 'psm_');
